site_name: My Library Documentation

theme:
  name: material

repo_url: https://github.com/steven-terrana/jte-library-scaffold.git

plugins:
  - search:
  - gen-files:
      scripts:
        - /docs/resources/copy_docs.py

extra:
  version:
    provider: mike
    default: latest

markdown_extensions:
  - admonition